SharkNetSniffer
hak5/sharkjack-payloads pull request #65
Opened 2024-09-13 04:50 UTC by BuffBaby253

A payload for the Sharkjack that captures network traffic and saves it in the loot folder

2024-09-13 15:50 UTC, hak5peaks requested changes

2024-09-13 15:50 UTC, hak5peaks commented on payloads/library/Wireshark PCAP Capture/payload.sh
This is in the wrong directory. Please move your payload to a category. `payloads/library/**category**/Wireshark_PCAP_Capture/payload.sh` Also remove spaces in the directory name, replacing them with `-` or `_`

2024-09-15 15:44 UTC, BuffBaby253 commented on payloads/library/Wireshark PCAP Capture/payload.sh
will do, thank you

2024-09-15 22:29 UTC, hak5peaks requested changes

2024-09-15 22:29 UTC, hak5peaks commented on payloads/library/recon/Shark-Net-Sniff/payload.sh
> +sleep 60
I would add a variable for sleep at the top of the payload. This makes it easier for the user to change the value. 
```
seconds=60
sleep $seconds
```

2024-09-16 22:18 UTC, hak5peaks requested changes

2024-09-17 19:20 UTC, BuffBaby253 reviewed
right that's much better thank you

2024-09-17 22:02 UTC, merged